Added to only fail on some errors

diff --git a/mkvalidator b/mkvalidator
--- a/mkvalidator
+++ b/mkvalidator
@@ -1,5 +1,17 @@
 #!/bin/bash
 . /etc/environment
+FAILON=("ERR066" "ERR068")
+
+ArrContains(){
+  local lArr1 lArr2
+  declare -A tmp
+  eval lArr1=("\"\${$1[@]}\"")
+  eval lArr2=("\"\${$2[@]}\"")
+  for i in "${lArr1[@]}";{ ((++tmp['$i']));}
+  for i in "${lArr2[@]}";{ [ -n "${tmp[$i]}" ] && return 0;}
+  return 1
+}
+
 echo "Searching $1 for largest mkv file"
 MKV=$(find $1 -name '*.mkv' -printf '%s "%p"\n'|sort -nr|head -n 1|cut -d '"' -f 2)
 if [ -z "$MKV" ]; then 
@@ -7,11 +19,13 @@ if [ -z "$MKV" ]; then
   exit 0
 fi
 echo "Validating $MKV"
-/usr/local/bin/mkvalidator --quiet "$MKV"
+OUTPUT=$((/usr/local/bin/mkvalidator --quiet "$MKV") 2>&1)
 STATUS=$?
+echo "$OUTPUT"
 if [ $STATUS -ne 0 ]; then
-  echo "Oh Bugger, errors found!"
-  exit $STATUS  
+  echo "Oh bugger, errors :("
+  ERR=($(echo "$OUTPUT" | awk -F '[\r:]' '/ERR/{print $2}'))
+  ArrContains FAILON ERR && exit -1 || exit 0
 fi
 
 echo "No errors :)"
